# -*- coding: utf-8 -*-

from core.db import add_word


def import_words():
    added = 0

    words =[
        {"category":"غذا","word":"کوکو سیب زمینی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"کوکو با سیب زمینی"},
        {"category":"غذا","word":"رولت گوشت","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"غذای گوشتی"},
        {"category":"غذا","word":"جوجه کباب","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"کباب مرغ"},
        {"category":"غذا","word":"کباب برگ","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نوعی کباب"},
        {"category":"غذا","word":"کباب کوبیده","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"کباب چرخ‌کرده"},
        {"category":"غذا","word":"کباب سلطانی","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"کباب مجلسی"},
        {"category":"غذا","word":"شیشلیک","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"کباب دنده"},
        {"category":"غذا","word":"اکبر جوجه","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"غذای شمالی"},
        {"category":"غذا","word":"خوراک لوبیا","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"خوراک حبوبات"},
        {"category":"غذا","word":"خوراک قارچ","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"غذای گیاهی"},
        {"category":"غذا","word":"خوراک مرغ","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"مرغ پخته"},
        {"category":"غذا","word":"خوراک گوشت","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"غذای گوشتی"},
        {"category":"غذا","word":"خوراک زبان","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"غذای تهیه‌شده از زبان"},
        {"category":"غذا","word":"دل و جگر","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"غذای کبابی"},
        {"category":"غذا","word":"سیرابی","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"غذای سنتی"},
        {"category":"غذا","word":"کله پاچه","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"صبحانه سنتی"},
        {"category":"غذا","word":"حلیم","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"صبحانه معروف"},
        {"category":"غذا","word":"شله زرد","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"دسر زعفرانی"},
        {"category":"غذا","word":"فرنی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"دسر شیری"},
        {"category":"غذا","word":"شیر برنج","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"دسر برنجی"},
        {"category":"غذا","word":"حلوا","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"شیرینی سنتی"},
        {"category":"غذا","word":"باقلوا","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"شیرینی لایه‌ای"},
        {"category":"غذا","word":"زولبیا","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"شیرینی رمضان"},
        {"category":"غذا","word":"بامیه","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"شیرینی سرخ‌شده"},
        {"category":"غذا","word":"کیک شکلاتی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"دسر شکلاتی"},
        {"category":"غذا","word":"کیک وانیلی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"کیک ساده"},
        {"category":"غذا","word":"دونات","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"شیرینی حلقه‌ای"},
        {"category":"غذا","word":"پنکیک","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"صبحانه شیرین"},
        {"category":"غذا","word":"وافل","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"شیرینی شبکه‌ای"},
        {"category":"غذا","word":"تیرامیسو","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"دسر ایتالیایی"},
        {"category":"غذا","word":"پاستا","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"غذای ایتالیایی"},
        {"category":"غذا","word":"راویولی","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"پاستای شکم‌پر"},
        {"category":"غذا","word":"فتوچینی","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"نوعی پاستا"},
        {"category":"غذا","word":"پنه آلفردو","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"پاستا با سس آلفردو"},
        {"category":"غذا","word":"ماکارونی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"غذای محبوب"},
        {"category":"غذا","word":"رشته پلو","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"پلوی سنتی"},
        {"category":"غذا","word":"دمپختک","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"برنج ساده"},
        {"category":"غذا","word":"استانبولی","difficulty":1,"rarity":1,"points":10,"synonyms":"استانبولی پلو","clue":"پلو با گوجه"},
        {"category":"غذا","word":"کلم پلو","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"غذای شیرازی"},
        {"category":"غذا","word":"سبزی پلو","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"پلو با سبزی"},
        {"category":"غذا","word":"ماهی پلو","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"پلو با ماهی"},
        {"category":"غذا","word":"میگو پلو","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"پلو دریایی"},
        {"category":"غذا","word":"زرشک مرغ","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"مرغ با زرشک"},
        {"category":"غذا","word":"مرغ شکم پر","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"مرغ پرشده"},
        {"category":"غذا","word":"ماهی شکم پر","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"غذای شمالی"},
        {"category":"غذا","word":"قلیه ماهی","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"خورشت جنوبی"},
        {"category":"غذا","word":"قلیه میگو","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"غذای جنوبی"},
        {"category":"غذا","word":"میگو سوخاری","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"غذای دریایی"},
        {"category":"غذا","word":"ماهی سوخاری","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"ماهی سرخ‌شده"},
        {"category":"غذا","word":"استیک","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"گوشت گریل‌شده"},
        {"category":"غذا","word":"بیف استراگانف","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"غذای روسی"},
        {"category":"غذا","word":"چیکن استراگانف","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"استراگانف مرغ"},
        {"category":"غذا","word":"رست بیف","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"گوشت بریان"},
        {"category":"غذا","word":"کتلت","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"غذای سیب زمینی و گوشت"},
        {"category":"غذا","word":"شامی","difficulty":1,"rarity":1,"points":10,"synonyms":"شامی کباب","clue":"غذای گوشتی"},
        {"category":"غذا","word":"یتیمچه","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"غذای بادمجان"},
        {"category":"غذا","word":"خوراک عدسی","difficulty":1,"rarity":1,"points":10,"synonyms":"عدسی","clue":"صبحانه محبوب"},
        {"category":"غذا","word":"آب دوغ خیار","difficulty":1,"rarity":2,"points":12,"synonyms":"آبدوغ خیار","clue":"غذای سرد"},
        {"category":"غذا","word":"سالاد شیرازی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"سالاد ایرانی"},
        {"category":"غذا","word":"سالاد سزار","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"سالاد معروف"},
        {"category":"غذا","word":"سالاد فصل","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"سالاد سبزیجات"},
        {"category":"غذا","word":"سالاد الویه","difficulty":1,"rarity":1,"points":10,"synonyms":"الویه","clue":"سالاد با سیب‌زمینی"},
        {"category":"غذا","word":"سالاد ماکارونی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"سالاد سرد"},
        {"category":"غذا","word":"سالاد یونانی","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"سالاد مدیترانه‌ای"},
        {"category":"غذا","word":"سالاد کلم","difficulty":1,"rarity":1,"points":10,"synonyms":"کولسلا","clue":"سالاد با کلم"},
        {"category":"غذا","word":"بورانی اسفناج","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"پیش‌غذای ماستی"},
        {"category":"غذا","word":"بورانی بادمجان","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"بادمجان و ماست"},
        {"category":"غذا","word":"بورانی لبو","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"لبو و ماست"},
        {"category":"غذا","word":"ماست و خیار","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"پیش‌غذای سرد"},
        {"category":"غذا","word":"ماست موسیر","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"ماست طعم‌دار"},
        {"category":"غذا","word":"زیتون پرورده","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"چاشنی شمالی"},
        {"category":"غذا","word":"ترشی لیته","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"ترشی خردشده"},
        {"category":"غذا","word":"ترشی سیر","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"ترشی چندساله"},
        {"category":"غذا","word":"ترشی مخلوط","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"ترشی سبزیجات"},
        {"category":"غذا","word":"خیارشور","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"چاشنی شور"},
        {"category":"غذا","word":"شور","difficulty":1,"rarity":2,"points":12,"synonyms":"سبزی شور","clue":"چاشنی سنتی"},
        {"category":"غذا","word":"نان سنگک","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نان ایرانی"},
        {"category":"غذا","word":"نان بربری","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نان سنتی"},
        {"category":"غذا","word":"نان تافتون","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نان گرد"},
        {"category":"غذا","word":"نان لواش","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نان نازک"},
        {"category":"غذا","word":"نان تست","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نان صبحانه"},
        {"category":"غذا","word":"نان سیر","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نان طعم‌دار"},
        {"category":"غذا","word":"نان سیر و پنیر","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"پیش‌غذا"},
        {"category":"غذا","word":"نان خامه‌ای","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"شیرینی خامه‌ای"},
        {"category":"غذا","word":"نان شکلاتی","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نان شیرین"},
        {"category":"غذا","word":"کروسان","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نان فرانسوی"},
        {"category":"غذا","word":"مافین","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"کیک کوچک"},
        {"category":"غذا","word":"براونی","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"کیک شکلاتی"},
        {"category":"غذا","word":"چیزکیک","difficulty":2,"rarity":2,"points":12,"synonyms":"چیز کیک","clue":"دسر پنیری"},
        {"category":"غذا","word":"پودینگ","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"دسر نرم"},
        {"category":"غذا","word":"سالاد فصل","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"سالاد سبزیجات"},
        {"category":"غذا","word":"سالاد الویه","difficulty":1,"rarity":1,"points":10,"synonyms":"الویه","clue":"سالاد با سیب‌زمینی"},
        {"category":"غذا","word":"سالاد ماکارونی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"سالاد سرد"},
        {"category":"غذا","word":"سالاد یونانی","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"سالاد مدیترانه‌ای"},
        {"category":"غذا","word":"سالاد کلم","difficulty":1,"rarity":1,"points":10,"synonyms":"کولسلا","clue":"سالاد با کلم"},
        {"category":"غذا","word":"بورانی اسفناج","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"پیش‌غذای ماستی"},
        {"category":"غذا","word":"بورانی بادمجان","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"بادمجان و ماست"},
        {"category":"غذا","word":"بورانی لبو","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"لبو و ماست"},
        {"category":"غذا","word":"ماست و خیار","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"پیش‌غذای سرد"},
        {"category":"غذا","word":"ماست موسیر","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"ماست طعم‌دار"},
        {"category":"غذا","word":"زیتون پرورده","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"چاشنی شمالی"},
        {"category":"غذا","word":"ترشی لیته","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"ترشی خردشده"},
        {"category":"غذا","word":"ترشی سیر","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"ترشی چندساله"},
        {"category":"غذا","word":"ترشی مخلوط","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"ترشی سبزیجات"},
        {"category":"غذا","word":"خیارشور","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"چاشنی شور"},
        {"category":"غذا","word":"شور","difficulty":1,"rarity":2,"points":12,"synonyms":"سبزی شور","clue":"چاشنی سنتی"},
        {"category":"غذا","word":"نان سنگک","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نان ایرانی"},
        {"category":"غذا","word":"نان بربری","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نان سنتی"},
        {"category":"غذا","word":"نان تافتون","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نان گرد"},
        {"category":"غذا","word":"نان لواش","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نان نازک"},
        {"category":"غذا","word":"نان تست","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نان صبحانه"},
        {"category":"غذا","word":"نان سیر","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نان طعم‌دار"},
        {"category":"غذا","word":"نان سیر و پنیر","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"پیش‌غذا"},
        {"category":"غذا","word":"نان خامه‌ای","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"شیرینی خامه‌ای"},
        {"category":"غذا","word":"نان شکلاتی","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نان شیرین"},
        {"category":"غذا","word":"کروسان","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نان فرانسوی"},
        {"category":"غذا","word":"مافین","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"کیک کوچک"},
        {"category":"غذا","word":"براونی","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"کیک شکلاتی"},
        {"category":"غذا","word":"چیزکیک","difficulty":2,"rarity":2,"points":12,"synonyms":"چیز کیک","clue":"دسر پنیری"},
        {"category":"غذا","word":"پودینگ","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"دسر نرم"},{"category":"اسم","word":"آراد","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"آرمان","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"آرش","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"قهرمان اسطوره‌ای"},
        {"category":"اسم","word":"آبتین","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"آریا","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"آرین","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"آرمین","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"امیر","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"امیرعلی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"امیرحسین","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"امیرمحمد","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"امیررضا","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"احسان","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"احمد","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"اکبر","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"امید","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"ایلیا","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"ایمان","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"ابوالفضل","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"ابراهیم","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پیامبر"},
        {"category":"اسم","word":"اسماعیل","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پیامبر"},
        {"category":"اسم","word":"اسحاق","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"نام پیامبر"},
        {"category":"اسم","word":"اصغر","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"افشین","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"اشکان","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"اردلان","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"ارسلان","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"ارشیا","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"ادیب","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"امین","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"محمد","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"محمدرضا","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"محمدحسین","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"محمدمهدی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"محمدامین","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"مهدی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"مصطفی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"محسن","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"مجتبی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"مرتضی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"میلاد","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"میثم","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"مسعود","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"مبین","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"مانی","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"ماهان","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"مازیار","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"مهران","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"مهراد","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"مهرشاد","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"مهرانگیز","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"مهسا","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"مریم","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"مینا","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"ملیکا","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"محدثه","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"مرضیه","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"معصومه","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"مژگان","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"مهشید","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"عباس","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"عبدالله","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"عبدالرضا","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"عبدالحسین","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"عرفان","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"عارف","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"عادل","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"عمران","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"عماد","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"عطا","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"عطاالله","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"عقیل","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"نام پسر"},
        {"category":"اسم","word":"عارفه","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"عاطفه","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"عذرا","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"عسل","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"عشرت","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"عفت","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"عصمت","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"عارفه‌سادات","difficulty":3,"rarity":4,"points":20,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"عالیه","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"عطیه","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"عصماء","difficulty":3,"rarity":4,"points":20,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"عقیقه","difficulty":3,"rarity":4,"points":20,"synonyms":"","clue":"نام دختر"},
        {"category":"اسم","word":"عشرت‌السادات","difficulty":3,"rarity":5,"points":25,"synonyms":"","clue":"نام دختر"},
        {"category":"ماشین","word":"پراید","difficulty":1,"rarity":1,"points":10,"synonyms":"پراید 131","clue":"خودروی اقتصادی سایپا"},
        {"category":"ماشین","word":"پژو 206","difficulty":1,"rarity":1,"points":10,"synonyms":"206","clue":"هاچ‌بک محبوب"},
        {"category":"ماشین","word":"پژو 207","difficulty":1,"rarity":1,"points":10,"synonyms":"207","clue":"نسخه جدید 206"},
        {"category":"ماشین","word":"پژو 405","difficulty":1,"rarity":1,"points":10,"synonyms":"405","clue":"سدان ایران‌خودرو"},
        {"category":"ماشین","word":"پارس","difficulty":1,"rarity":1,"points":10,"synonyms":"پژو پارس","clue":"سدان محبوب"},
        {"category":"ماشین","word":"سمند","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"خودروی ملی"},
        {"category":"ماشین","word":"دنا","difficulty":1,"rarity":1,"points":10,"synonyms":"دنا پلاس","clue":"محصول ایران‌خودرو"},
        {"category":"ماشین","word":"رانا","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"سدان ایران‌خودرو"},
        {"category":"ماشین","word":"تارا","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"سدان جدید"},
        {"category":"ماشین","word":"شاهین","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"سدان سایپا"},
        {"category":"ماشین","word":"اطلس","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"محصول جدید سایپا"},
        {"category":"ماشین","word":"سهند","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"خودروی جدید سایپا"},
        {"category":"ماشین","word":"تیبا","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"محصول سایپا"},
        {"category":"ماشین","word":"تیبا 2","difficulty":1,"rarity":2,"points":12,"synonyms":"تیبا دو","clue":"هاچ‌بک تیبا"},
        {"category":"ماشین","word":"ساینا","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"سدان سایپا"},
        {"category":"ماشین","word":"کوییک","difficulty":1,"rarity":1,"points":10,"synonyms":"","clue":"هاچ‌بک سایپا"},
        {"category":"ماشین","word":"ری‌را","difficulty":2,"rarity":3,"points":15,"synonyms":"ری را","clue":"کراس‌اوور ایران‌خودرو"},
        {"category":"ماشین","word":"پیکان","difficulty":1,"rarity":2,"points":12,"synonyms":"","clue":"خودروی نوستالژیک"},
        {"category":"ماشین","word":"روآ","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"نسخه ارتقایافته پیکان"},
        {"category":"ماشین","word":"آریسان","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"وانت ایران‌خودرو"},
        {"category":"ماشین","word":"وانت نیسان","difficulty":1,"rarity":2,"points":12,"synonyms":"نیسان آبی","clue":"وانت معروف"},
        {"category":"ماشین","word":"مزدا 3","difficulty":1,"rarity":2,"points":12,"synonyms":"Mazda 3","clue":"سدان ژاپنی"},
        {"category":"ماشین","word":"مزدا 2","difficulty":2,"rarity":3,"points":15,"synonyms":"Mazda 2","clue":"هاچ‌بک ژاپنی"},
        {"category":"ماشین","word":"تویوتا کرولا","difficulty":1,"rarity":2,"points":12,"synonyms":"کرولا","clue":"سدان ژاپنی"},
        {"category":"ماشین","word":"تویوتا کمری","difficulty":1,"rarity":2,"points":12,"synonyms":"کمری","clue":"سدان محبوب"},
        {"category":"ماشین","word":"تویوتا لندکروزر","difficulty":2,"rarity":3,"points":15,"synonyms":"لندکروزر","clue":"شاسی‌بلند معروف"},
        {"category":"ماشین","word":"تویوتا پرادو","difficulty":2,"rarity":3,"points":15,"synonyms":"پرادو","clue":"شاسی‌بلند"},
        {"category":"ماشین","word":"هیوندای سوناتا","difficulty":2,"rarity":3,"points":15,"synonyms":"سوناتا","clue":"سدان کره‌ای"},
        {"category":"ماشین","word":"هیوندای النترا","difficulty":2,"rarity":3,"points":15,"synonyms":"النترا","clue":"سدان کره‌ای"},
        {"category":"ماشین","word":"کیا سراتو","difficulty":2,"rarity":3,"points":15,"synonyms":"سراتو","clue":"سدان کره‌ای"},
        {"category":"ماشین","word":"کیا اپتیما","difficulty":2,"rarity":3,"points":15,"synonyms":"اپتیما","clue":"سدان کره‌ای"},
        {"category":"ماشین","word":"کیا اسپورتیج","difficulty":2,"rarity":3,"points":15,"synonyms":"اسپورتیج","clue":"شاسی‌بلند کره‌ای"},
        {"category":"ماشین","word":"کیا سورنتو","difficulty":2,"rarity":3,"points":15,"synonyms":"سورنتو","clue":"SUV کره‌ای"},
        {"category":"ماشین","word":"هیوندای توسان","difficulty":2,"rarity":3,"points":15,"synonyms":"توسان","clue":"شاسی‌بلند کره‌ای"},
        {"category":"ماشین","word":"هیوندای سانتافه","difficulty":2,"rarity":3,"points":15,"synonyms":"سانتافه","clue":"SUV محبوب"},
        {"category":"ماشین","word":"هیوندای آزرا","difficulty":2,"rarity":3,"points":15,"synonyms":"آزرا","clue":"سدان لوکس"},
        {"category":"ماشین","word":"هیوندای جنسیس","difficulty":3,"rarity":4,"points":20,"synonyms":"جنسیس","clue":"سدان لوکس"},
        {"category":"ماشین","word":"نیسان ماکسیما","difficulty":2,"rarity":3,"points":15,"synonyms":"ماکسیما","clue":"سدان ژاپنی"},
        {"category":"ماشین","word":"نیسان رونیز","difficulty":2,"rarity":3,"points":15,"synonyms":"رونیز","clue":"شاسی‌بلند نیسان"},
        {"category":"ماشین","word":"نیسان ایکس تریل","difficulty":3,"rarity":4,"points":20,"synonyms":"ایکس تریل","clue":"SUV نیسان"},
        {"category":"ماشین","word":"نیسان جوک","difficulty":2,"rarity":3,"points":15,"synonyms":"جوک","clue":"کراس‌اوور نیسان"},
        {"category":"ماشین","word":"نیسان قشقایی","difficulty":2,"rarity":3,"points":15,"synonyms":"قشقایی","clue":"کراس‌اوور نیسان"},
        {"category":"ماشین","word":"رنو ال 90","difficulty":1,"rarity":2,"points":12,"synonyms":"تندر 90","clue":"سدان رنو"},
        {"category":"ماشین","word":"رنو ساندرو","difficulty":2,"rarity":3,"points":15,"synonyms":"ساندرو","clue":"هاچ‌بک رنو"},
        {"category":"ماشین","word":"رنو کپچر","difficulty":2,"rarity":3,"points":15,"synonyms":"کپچر","clue":"کراس‌اوور رنو"},
        {"category":"ماشین","word":"رنو مگان","difficulty":2,"rarity":3,"points":15,"synonyms":"مگان","clue":"سدان فرانسوی"},
        {"category":"ماشین","word":"چری آریزو 5","difficulty":2,"rarity":3,"points":15,"synonyms":"آریزو 5","clue":"سدان چینی"},
        {"category":"ماشین","word":"چری تیگو 7","difficulty":2,"rarity":3,"points":15,"synonyms":"تیگو 7","clue":"SUV چینی"},
        {"category":"ماشین","word":"چری تیگو 8","difficulty":3,"rarity":4,"points":20,"synonyms":"تیگو 8","clue":"شاسی‌بلند چینی"},
        {"category":"ماشین","word":"ام وی ام 110","difficulty":2,"rarity":3,"points":15,"synonyms":"MVM 110","clue":"هاچ‌بک کوچک"},
        {"category":"ماشین","word":"ام وی ام 315","difficulty":2,"rarity":3,"points":15,"synonyms":"MVM 315","clue":"هاچ‌بک چینی"},
        {"category":"ماشین","word":"ام وی ام X22","difficulty":2,"rarity":3,"points":15,"synonyms":"X22","clue":"کراس‌اوور"},
        {"category":"ماشین","word":"ام وی ام X33","difficulty":2,"rarity":3,"points":15,"synonyms":"X33","clue":"شاسی‌بلند"},
        {"category":"ماشین","word":"جک S5","difficulty":2,"rarity":3,"points":15,"synonyms":"S5","clue":"SUV جک"},
        {"category":"ماشین","word":"جک J5","difficulty":2,"rarity":3,"points":15,"synonyms":"J5","clue":"سدان جک"},
        {"category":"ماشین","word":"لاماری ایما","difficulty":3,"rarity":4,"points":20,"synonyms":"ایما","clue":"کراس‌اوور جدید"},
        {"category":"ماشین","word":"فیدلیتی","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"SUV بهمن موتور"},
        {"category":"ماشین","word":"دیگنیتی","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"کراس‌اوور بهمن"},
        {"category":"ماشین","word":"فونیکس FX","difficulty":3,"rarity":4,"points":20,"synonyms":"FX","clue":"کراس‌اوور فونیکس"},
        {"category":"ماشین","word":"اکستریم VX","difficulty":3,"rarity":5,"points":25,"synonyms":"VX","clue":"شاسی‌بلند لوکس"},
        {"category":"ماشین","word":"آلفا رومئو جولیا","difficulty":4,"rarity":5,"points":25,"synonyms":"جولیا","clue":"سدان ایتالیایی"},
        {"category":"ماشین","word":"آلفا رومئو استلویو","difficulty":4,"rarity":5,"points":25,"synonyms":"استلویو","clue":"شاسی‌بلند ایتالیایی"},
        {"category":"ماشین","word":"آئودی A3","difficulty":3,"rarity":4,"points":20,"synonyms":"A3","clue":"سدان آلمانی"},
        {"category":"ماشین","word":"آئودی A4","difficulty":3,"rarity":4,"points":20,"synonyms":"A4","clue":"سدان آلمانی"},
        {"category":"ماشین","word":"آئودی A6","difficulty":3,"rarity":4,"points":20,"synonyms":"A6","clue":"سدان لوکس"},
        {"category":"ماشین","word":"آئودی Q3","difficulty":3,"rarity":4,"points":20,"synonyms":"Q3","clue":"کراس‌اوور آلمانی"},
        {"category":"ماشین","word":"آئودی Q5","difficulty":3,"rarity":4,"points":20,"synonyms":"Q5","clue":"SUV آلمانی"},
        {"category":"ماشین","word":"آئودی Q7","difficulty":4,"rarity":5,"points":25,"synonyms":"Q7","clue":"شاسی‌بلند لوکس"},
        {"category":"ماشین","word":"بی ام و 116i","difficulty":3,"rarity":4,"points":20,"synonyms":"116i","clue":"هاچ‌بک BMW"},
        {"category":"ماشین","word":"بی ام و 120i","difficulty":3,"rarity":4,"points":20,"synonyms":"120i","clue":"هاچ‌بک BMW"},
        {"category":"ماشین","word":"بی ام و 320i","difficulty":2,"rarity":3,"points":15,"synonyms":"320i","clue":"سدان BMW"},
        {"category":"ماشین","word":"بی ام و 325i","difficulty":3,"rarity":4,"points":20,"synonyms":"325i","clue":"سدان BMW"},
        {"category":"ماشین","word":"بی ام و 330i","difficulty":3,"rarity":4,"points":20,"synonyms":"330i","clue":"سدان اسپرت"},
        {"category":"ماشین","word":"بی ام و 520i","difficulty":2,"rarity":3,"points":15,"synonyms":"520i","clue":"سدان لوکس"},
        {"category":"ماشین","word":"بی ام و 530i","difficulty":3,"rarity":4,"points":20,"synonyms":"530i","clue":"سدان لوکس"},
        {"category":"ماشین","word":"بی ام و 730Li","difficulty":4,"rarity":5,"points":25,"synonyms":"730Li","clue":"سدان پرچمدار"},
        {"category":"ماشین","word":"بی ام و X1","difficulty":3,"rarity":4,"points":20,"synonyms":"X1","clue":"کراس‌اوور BMW"},
        {"category":"ماشین","word":"بی ام و X3","difficulty":3,"rarity":4,"points":20,"synonyms":"X3","clue":"SUV BMW"},
        {"category":"ماشین","word":"بی ام و X5","difficulty":3,"rarity":4,"points":20,"synonyms":"X5","clue":"شاسی‌بلند لوکس"},
        {"category":"ماشین","word":"بی ام و X6","difficulty":3,"rarity":4,"points":20,"synonyms":"X6","clue":"SUV کوپه"},
        {"category":"ماشین","word":"مرسدس بنز C200","difficulty":3,"rarity":4,"points":20,"synonyms":"C200","clue":"سدان مرسدس"},
        {"category":"ماشین","word":"مرسدس بنز E200","difficulty":3,"rarity":4,"points":20,"synonyms":"E200","clue":"سدان لوکس"},
        {"category":"ماشین","word":"مرسدس بنز E350","difficulty":4,"rarity":5,"points":25,"synonyms":"E350","clue":"سدان مرسدس"},
        {"category":"ماشین","word":"مرسدس بنز S500","difficulty":4,"rarity":5,"points":25,"synonyms":"S500","clue":"پرچمدار مرسدس"},
        {"category":"ماشین","word":"مرسدس بنز CLS","difficulty":4,"rarity":5,"points":25,"synonyms":"CLS","clue":"کوپه چهاردر"},
        {"category":"ماشین","word":"مرسدس بنز GLA","difficulty":3,"rarity":4,"points":20,"synonyms":"GLA","clue":"کراس‌اوور مرسدس"},
        {"category":"ماشین","word":"مرسدس بنز GLC","difficulty":3,"rarity":4,"points":20,"synonyms":"GLC","clue":"SUV مرسدس"},
        {"category":"ماشین","word":"مرسدس بنز GLE","difficulty":4,"rarity":5,"points":25,"synonyms":"GLE","clue":"شاسی‌بلند لوکس"},
        {"category":"ماشین","word":"مرسدس بنز G کلاس","difficulty":4,"rarity":5,"points":25,"synonyms":"جی کلاس","clue":"شاسی‌بلند افسانه‌ای"},
        {"category":"ماشین","word":"پورشه کاین","difficulty":3,"rarity":4,"points":20,"synonyms":"کاین","clue":"SUV پورشه"},
        {"category":"ماشین","word":"چری","difficulty":1,"rarity":2,"points":12,"synonyms":"Chery","clue":"خودروساز چینی"},
        {"category":"ماشین","word":"ام وی ام","difficulty":1,"rarity":2,"points":12,"synonyms":"MVM","clue":"برند مونتاژی"},
        {"category":"ماشین","word":"اکستریم","difficulty":2,"rarity":3,"points":15,"synonyms":"XTRIM","clue":"برند لوکس مدیران خودرو"},
        {"category":"ماشین","word":"لاماری","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"کراس‌اوور ایرانی"},
        {"category":"ماشین","word":"فیدلیتی","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"محصول بهمن"},
        {"category":"ماشین","word":"دیگنیتی","difficulty":2,"rarity":2,"points":12,"synonyms":"","clue":"شاسی‌بلند بهمن"},
        {"category":"ماشین","word":"ریسپکت","difficulty":2,"rarity":3,"points":15,"synonyms":"","clue":"سدان بهمن"},
        {"category":"ماشین","word":"کی ام سی","difficulty":2,"rarity":2,"points":12,"synonyms":"KMC","clue":"برند کرمان موتور"},
        {"category":"ماشین","word":"جک","difficulty":1,"rarity":1,"points":10,"synonyms":"JAC","clue":"برند چینی"},
        {"category":"ماشین","word":"لیفان","difficulty":1,"rarity":2,"points":12,"synonyms":"Lifan","clue":"خودروساز چینی"},
        {"category":"ماشین","word":"هایما","difficulty":1,"rarity":2,"points":12,"synonyms":"Haima","clue":"برند مونتاژی"},
        {"category":"ماشین","word":"فاو","difficulty":2,"rarity":3,"points":15,"synonyms":"FAW","clue":"خودروساز چینی"},
        {"category":"ماشین","word":"بسترن","difficulty":2,"rarity":3,"points":15,"synonyms":"Bestune","clue":"زیرمجموعه فاو"},
        {"category":"ماشین","word":"دانگ فنگ","difficulty":2,"rarity":3,"points":15,"synonyms":"Dongfeng","clue":"خودروساز چینی"},
        {"category":"ماشین","word":"هونگچی","difficulty":3,"rarity":4,"points":18,"synonyms":"Hongqi","clue":"برند لوکس چین"},
        {"category":"ماشین","word":"جیلی","difficulty":2,"rarity":3,"points":15,"synonyms":"Geely","clue":"مالک ولوو"},
        {"category":"ماشین","word":"چانگان","difficulty":2,"rarity":2,"points":12,"synonyms":"Changan","clue":"برند چینی"},
        {"category":"ماشین","word":"گریت وال","difficulty":2,"rarity":3,"points":15,"synonyms":"Great Wall","clue":"سازنده هاوال"},
        {"category":"ماشین","word":"هاوال","difficulty":2,"rarity":2,"points":12,"synonyms":"Haval","clue":"شاسی‌بلند چینی"},
        {"category":"ماشین","word":"بی وای دی","difficulty":2,"rarity":3,"points":15,"synonyms":"BYD","clue":"خودروساز برقی"},
        {"category":"ماشین","word":"نیو","difficulty":3,"rarity":4,"points":18,"synonyms":"NIO","clue":"برند برقی چین"},
        {"category":"ماشین","word":"اکس پنگ","difficulty":3,"rarity":4,"points":18,"synonyms":"XPeng","clue":"خودروساز برقی"},
        {"category":"ماشین","word":"زیکر","difficulty":3,"rarity":4,"points":18,"synonyms":"Zeekr","clue":"برند برقی جیلی"},
        {"category":"ماشین","word":"رووی","difficulty":3,"rarity":4,"points":18,"synonyms":"Roewe","clue":"برند چینی"},
        {"category":"ماشین","word":"ام جی","difficulty":2,"rarity":2,"points":12,"synonyms":"MG","clue":"برند انگلیسی-چینی"},
        {"category":"ماشین","word":"پروتون","difficulty":2,"rarity":3,"points":15,"synonyms":"Proton","clue":"خودروساز مالزی"},
        {"category":"ماشین","word":"پرودوا","difficulty":3,"rarity":4,"points":18,"synonyms":"Perodua","clue":"برند مالزی"},
        {"category":"ماشین","word":"تاتا","difficulty":2,"rarity":3,"points":15,"synonyms":"Tata","clue":"خودروساز هندی"},
        {"category":"ماشین","word":"ماهندرا","difficulty":2,"rarity":3,"points":15,"synonyms":"Mahindra","clue":"خودروساز هند"},
        {"category":"ماشین","word":"اشکودا","difficulty":2,"rarity":3,"points":15,"synonyms":"Skoda","clue":"برند جمهوری چک"},
    ]

    for item in words:
        if add_word(
            item["category"],
            item["word"],
            item["difficulty"],
            item["rarity"],
            item["points"],
            item["synonyms"],
            item["clue"],
        ):
            added += 1

    print(f"Added {added} words.")


if __name__ == "__main__":
    import_words()